<?php
/**
 * Codifi_CustomerRequest
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var Codifi\CustomerRequest\Block\Request\Form $block
 */
?>
<div class="customer-request-form">
    <form action="<?= $block->escapeUrl($block->getSubmitUrl()) ?>" method="post">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="customer_id" value="<?= $block->escapeHtml($block->getCustomerId()) ?>"/>
            <div class="field required">
                <label for="customer_name" class="label">
                    <span><?= $block->escapeHtml(__('Name')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="customer_name" value="<?= $block->escapeHtml($block->getCustomerName()) ?>"/>
                </div>
            </div>
            <div class="field required">
                <label for="customer_email" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="customer_email" value="<?= $block->escapeHtml($block->getCustomerEmail()) ?>"/>
                </div>
            </div>
            <div class="field required">
                <label for="customer_messsage" class="label">
                    <span><?= $block->escapeHtml(__('Message')) ?></span>
                </label>
                <div class="control">
                    <textarea name="customer_messsage" maxlength="255"></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?= $block->escapeHtml(__('Submit')) ?>">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
