<?php
/**
 * Codifi_Sales
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var \Codifi\Sales\Block\Adminhtml\Order\View\Create $block
 */
?>
<fieldset class="fieldset admin__fieldset " id="order_type_fieldset">
    <div class="messages">
    </div>
    <div class="admin__field field field-order_type required _required">
        <label class="label admin__field-label" for="order_type_select"><span>Order Type</span></label>
        <div class="admin__field-control control">
            <select id="order_type_select" name="order[order_type]" class="required-entry required-entry _required select admin__control-select">
                <?php foreach ($block->getAttributeValue() as $item) { ?>
                <option value="<?=$item['value']?>"><?=$item['label']?></option>
                <?php } ?>
            </select>
        </div>
    </div>
</fieldset>
<script>
    require(['Magento_Sales/order/create/form'], function() {
        $('order_type_select').observe('change', function() {
            order.saveData(order.serializeData('order-type'));
        });
    });
</script>
