<?php
/**
 * Codifi_Sales
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var \Codifi\Sales\Block\Adminhtml\Order\View\Info $block
 */
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Information')) ?></span>
    </div>
    <div class="admin__field">
        <label for="invoice_do_capture" class="admin__field-label">Order Type</label>
        <select class="admin__control-select">
            <option value="REGULAR">REGULAR ORDER</option>
            <option value="CREDIT_HOLD">CREDIT HOLD ORDER</option>
        </select>
    </div>
</section>
