<?php
/**
 * Codifi_Sales
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
$viewModel = $block->getViewModel();
$attributeValue = $viewModel->getAttributeValue();
?>
<fieldset class="fieldset admin__fieldset " id="order_type_fieldset">
    <div class="messages">
    </div>
    <div class="admin__field field field-order_type required _required">
        <label class="label admin__field-label" for="order_type_select"><span>Order Type</span></label>
        <div class="admin__field-control control">
            <select id="order_type_select" name="order_type" class="required-entry required-entry _required select admin__control-select">
                <?php foreach ($attributeValue as $item) { ?>
                    <option value="<?=$block->escapeHtml(__($item['value']))?>"><?=$block->escapeHtml(__($item['label']))?></option>
                <?php } ?>
            </select>
        </div>
    </div>
</fieldset>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ $(document).ready(function($) {
        var order_type = $('#order_type_select').val();
            if (order_type === 'CREDIT_HOLD') {
                $('#order_reorder').hide();
            }
        });
    });
</script>
