<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var Codifi\Training\Block\Adminhtml\Edit\Tab\View\PersonalInfo $block
 */
?>
<?php if ($block->checkForOneTimeDemoMessage()): ?>
    <div class="confirmation-modal-content">
        <p><?= $block->escapeHtml($block->getMessage()) ?></p>
    </div>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ], function ($) {
            'use strict';

            $('.confirmation-modal-content').confirm({
                buttons: [{
                    text: $.mage.__('OK'),
                    class: 'action primary action-accept',
                    click: function (event) {
                        this.closeModal(event, true);
                    }
                }]
            });
        });
    </script>
<?php endif; ?>

