<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
$viewModel = $block->getAdminSessionManagementViewModel();
?>
<?php if ($viewModel->checkBeforeDemo()): ?>
    <div class="confirmation-modal-content">
        <p><?= $block->escapeHtml($viewModel->getMessage()) ?></p>
    </div>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/confirm'
        ], function ($) {
            'use strict';

            $('.confirmation-modal-content').confirm({
                actions: {
                    always: function () {
                        $.ajax({
                            type: "POST",
                            url: "<?= $block->escapeJs($viewModel->getSaveIdUrl()) ?>",
                            data: {},
                            success: function (data) {
                            }
                        });
                    }
                },
                buttons: [{
                    text: $.mage.__('OK'),
                    class: 'action primary action-accept',
                    click: function (event) {
                        this.closeModal(event, true);
                    }
                }]
            });
        });
    </script>
<?php endif; ?>

