<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 */
$viewModel = $block->getCustomerSessionManagementViewModel();
$check = $viewModel->checkBeforeDemo();
?>
<div class="confirmation-modal-content" style="display: none;">
    <p><?= $block->escapeHtml($viewModel->getMessage()) ?></p>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "creditHold": {
                        "component": "Codifi_Training/js/popup",
                        "config": {
                            "url": "<?= $block->escapeJs($viewModel->getSaveUrl()) ?>",
                            "customerId": <?= $block->escapeJs($viewModel->getCustomerId()) ?>,
                            "checkOptionAndFlag": "<?= $block->escapeJs($check) ?>"
                        },
                        "children": {
                            "errors": {
                                "component": "Magento_Ui/js/view/messages",
                                "sortOrder": 0,
                                "displayArea": "messages",
                                "config": {
                                    "autoHideTimeOut": -1
                                }
                            }
                        }
                    }
                }
            }
        }
    }
</script>

