<?php
/**
 * Codifi_Training
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */

/**
 * @var Codifi\Training\Block\Account\Dashboard\CreditHold $block
 */
?>
<?php if ($block->checkForOneTimeDemoMessage()): ?>
    <div class="confirmation-modal-content" style="display: none;">
        <p><?= $block->escapeHtml($block->getMessage()) ?></p>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "creditHold": {
                        "component": "Codifi_Training/js/popup",
                        "config": {
                            "url": "<?= $block->escapeJs($block->getSaveUrl()) ?>",
                            "customerId": <?= $block->escapeJs($block->getCustomerId()) ?>
                        },
                        "children": {
                            "errors": {
                                "component": "Magento_Ui/js/view/messages",
                                "sortOrder": 0,
                                "displayArea": "messages",
                                "config": {
                                    "autoHideTimeOut": -1
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    </script>
<?php endif; ?>
