<?php
/**
 * Codifi_Sales
 *
 * @copyright   Copyright (c) 2021 Codifi
 * @author      Pavel Zelenevich <pzelenevich@codifi.me>
 */


/**
 * @var \Magento\Framework\View\Element\Template $block
 */
$viewModel = $block->getOrderCreateViewModel();
$orderTypeOptions = $viewModel->getOrderTypeOptions();
?>
<fieldset class="fieldset admin__fieldset " id="order_type_fieldset">
    <div class="admin__field field field-order_type required _required">
        <label class="label admin__field-label" for="order_type_select">
            <span><?= $block->escapeHtml(__('Order Type')) ?></span>
        </label>
        <div class="admin__field-control control">
            <select id="order_type_select" name="order[order_type]" class="required-entry _required select admin__control-select">
                <?php foreach ($orderTypeOptions as $item): ?>
                    <option value="<?= $block->escapeHtml(__($item['value'])) ?>"
                        <?= ($item['value'] === Codifi\Sales\Helper\Config::ORDER_TYPE_REGULAR_VALUE ) ? ' selected="selected"' : '' ?>>
                        <?= $block->escapeHtml(__($item['description'])) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</fieldset>
<script>
    require(['Magento_Sales/order/create/form'], function() {
        $('order_type_select').observe('change', function() {
            order.saveData(order.serializeData('order-type'));
        });
    });
</script>
