<div class="customer-credit-hold-section"data-bind="scope: 'section'">
    <p id="credit_hold" data-bind="text: customsection().customdata"></p>
</div>
<script type="text/x-magento-init">
    {
    	"*": {
        	"Magento_Ui/js/core/app": {
            	"components": {
                	"section": {
                    	"component": "Codifi_CustomerRequest/js/section"
                	}
            	}
        	}
    	}

    }
</script>
<script>
    require([
        'jquery',
        'jquery/ui'
    ], function($) {
        $(document).ready(function($) {
            var credit_hold = $('#credit_hold').text();
            if (credit_hold === 1) {
                console.log('adssdaYES!');
            }
        });
    });
</script>
